// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using logindemo.Data;

#nullable disable

namespace logindemo.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20230328104021_initial1")]
    partial class initial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "6F0A4D24-292F-4F7A-BC7D-0F59981F0F2C",
                            ConcurrencyStamp = "6F0A4D24-292F-4F7A-BC7D-0F59981F0F2E",
                            Name = "Read",
                            NormalizedName = "READ"
                        },
                        new
                        {
                            Id = "6F0A4D24-292F-4F7A-BC7D-0F59981F0F2D",
                            ConcurrencyStamp = "6F0A4D24-292F-4F7A-BC7D-0F59981F0F2E",
                            Name = "Write",
                            NormalizedName = "READ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
